version: '3'

services:
  kibana:
    image: kibana:6.5.4
    networks:
      - hankchan101
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_URL=http://elasticsearch:9200'
      - 'ELASTICSEARCH_USERNAME=elastic'
      - 'ELASTICSEARCH_PASSWORD=changeme'
      - 'XPACK_SECURITY_ENABLED=false'

networks:
  hankchan101:
    external: true
