version: '3'

services:
  namesrv:
    image: apache/rocketmq:4.3.0
    container_name: rmqnamesrv
#    networks:
#      - hankchan101
    ports:
      - "9876:9876"
    volumes:
      - ./data/namesrv/logs:/root/logs
      - ./data/namesrv/store:/root/store
    command: sh mqnamesrv

  broker:
    image: apache/rocketmq:4.3.0
    container_name: rmqbroker
#    networks:
#      - hankchan101
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - ./data/broker/logs:/root/logs
      - ./data/broker/store:/root/store
    command: sh mqbroker -n namesrv:9876
    depends_on:
      - namesrv

#networks:
#  hankchan101:
## if you want to make the link between 2 container on same network, driver is not needed, and set external true
#    driver: bridge
#    external: true


