version: '3'

services:
  redis:
    image: redis:4.0.12-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - hankchan101
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

networks:
  hankchan101:
    external: true
